name: pharmacy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/res/navigation_bar/image_basket_active.png
    - lib/res/navigation_bar/image_basket.png
    - lib/res/navigation_bar/image_catalog_active.png
    - lib/res/navigation_bar/image_catalog.png
    - lib/res/navigation_bar/image_favorite_active.png
    - lib/res/navigation_bar/image_favorites.png
    - lib/res/navigation_bar/image_main_active.png
    - lib/res/navigation_bar/image_main.png
    - lib/res/navigation_bar/image_profile_active.png
    - lib/res/navigation_bar/image_profile.png
    - lib/res/icons/alert.png
    - lib/res/icons/check.png
    - lib/res/icons/sale25.png
    - lib/res/icons/tmc.png
    - lib/res/icons/valutRu.png
    - lib/res/icons/map/komsomol33.png
    - lib/res/icons/map/lenin46.png
    - lib/res/icons/map/onlymap.png
    - lib/res/icons/map/pavlov932.png
    - lib/res/icons/map/pushkin6.png
    - lib/res/icons/avatar.png
    - lib/res/icons/image_notification.png
    - lib/res/icons/favorites_add.png
    - lib/res/icons/tmc2.png


  fonts:
  - family: FiraSans
    fonts:
     # --- Обычные начертания (style: normal) ---
     - asset: lib/res/fonts/FiraSans/FiraSans-Thin.ttf
       weight: 100
     - asset: lib/res/fonts/FiraSans/FiraSans-ExtraLight.ttf
       weight: 200
     - asset: lib/res/fonts/FiraSans/FiraSans-Light.ttf
       weight: 300
     - asset: lib/res/fonts/FiraSans/FiraSans-Regular.ttf
       weight: 400 # Regular
     - asset: lib/res/fonts/FiraSans/FiraSans-Medium.ttf
       weight: 500
     - asset: lib/res/fonts/FiraSans/FiraSans-SemiBold.ttf
       weight: 600
     - asset: lib/res/fonts/FiraSans/FiraSans-Bold.ttf
       weight: 700 # Bold
     - asset: lib/res/fonts/FiraSans/FiraSans-ExtraBold.ttf
       weight: 800
     - asset: lib/res/fonts/FiraSans/FiraSans-Black.ttf
       weight: 900 # Black, Heavy
     # --- Курсивные начертания (style: italic) ---
     - asset: lib/res/fonts/FiraSans/FiraSans-ThinItalic.ttf
       weight: 100
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-ExtraLightItalic.ttf
       weight: 200
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-LightItalic.ttf
       weight: 300
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-Italic.ttf
       weight: 400 # Italic (regular weight)
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-MediumItalic.ttf
       weight: 500
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-SemiBoldItalic.ttf
       weight: 600
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-BoldItalic.ttf
       weight: 700 # Bold Italic
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-ExtraBoldItalic.ttf
       weight: 800
       style: italic
     - asset: lib/res/fonts/FiraSans/FiraSans-BlackItalic.ttf
       weight: 900
       style: italic
